//
//  LocationStore.swift
//  Qatar-Challenge WatchKit Extension
//
//  Created by acrn on 30/11/22.
//

import Foundation
import MapKit

class LocationStore {
    
    var modelDict = [String: [Location]]()
    
    init() {
        modelDict["Futebol"] = [Location(name: "Arena Recife",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.futebol,
                                         category: "Campo de Futebol",
                                         free: false,
                                         address: "R. Álvares Píres, 16 - Cordeiro",
                                         time: "07-23",
                                         distance: nil),
                                Location(name: "Campo do Bueirão",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.futebol,
                                         category: "Campo de Futebol",
                                         free: false,
                                         address: "R. Zilda S de Santana - Torre",
                                         time: "07-23:30",
                                         distance: nil),
                                Location(name: "Campo Cacique",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.futebol,
                                         category: "Campo de Futebol",
                                         free: true,
                                         address: "Tv. Dr. Amaríles Barbosa de Águiar - Madalena",
                                         time: nil,
                                         distance: nil),
                                Location(name: "Society do Clube Internacional",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.futebol,
                                         category: "Campo de Futebol",
                                         free: false,
                                         address: "R. Prof. Benedito Monteiro, 56 - Madalena",
                                         time: "15-00",
                                         distance: nil),
                                Location(name: "Arena Bongi Society",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.futebol,
                                         category: "Campo de futebol",
                                         free: false,
                                         address: "R. Isaac Markman, 432 - Bongi",
                                         time: "15-22",
                                         distance: nil),
                                Location(name: "Play Side",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.futebol,
                                         category: "Campo de futebol",
                                         free: false,
                                         address: "R. Amália Bernardino de Sousa, 137 - Boa Viagem",
                                         time: "08-22:30",
                                         distance: nil),
                                Location(name: "Arena X1",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.futebol,
                                         category: "Campo de futebol",
                                         free: false,
                                         address: "R. Agricolândia, 64 - Várzea",
                                         time: "08-22",
                                         distance: nil)
        ]
        modelDict["Corrida"] = [Location(name: "Parque da Jaqueira",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.corrida,
                                         category: "Parque ao ar livre",
                                         free: true,
                                         address: "R. do Futuro - Graças",
                                         time: "04-22",
                                         distance: nil),
                                Location(name: "Avenida Boa Viagem",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.corrida,
                                         category: "Orla de praia",
                                         free: true,
                                         address: "Av. Boa Viagem - Boa Viagem",
                                         time: nil,
                                         distance: nil),
                                Location(name: "Parque Urbano da Macaxeira",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.corrida,
                                         category: "Parque ao ar livre",
                                         free: true,
                                         address: "Av. Norte Miguel Arraes de Alencar, s/n - Macaxeira",
                                         time: "05-22",
                                         distance: nil),
                                Location(name: "Praça de Casa Forte",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.corrida,
                                         category: "Parque ao ar livre",
                                         free: true,
                                         address: "Av. Dezessete de Agosto, 1387 - Parnamirim",
                                         time: nil,
                                         distance: nil),
                                Location(name: "Lagoa do Araçá",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.corrida,
                                         category: "Parque ao ar livre",
                                         free: true,
                                         address: "Lagoa do Araçá - Imbiribeira",
                                         time: nil,
                                         distance: nil),
                                Location(name: "Praça da Várzea",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.corrida,
                                         category: "Praça pública",
                                         free: true,
                                         address: "Praça da Várzea - Várzea",
                                         time: nil,
                                         distance: nil)
        ]
        modelDict["Tênis"] = [Location(name: "Recife Tenis Club",
                                       coordinate: <#T##CLLocationCoordinate2D#>,
                                       sport: PinSports.tenis,
                                       category: "Tênis Clube",
                                       free: false,
                                       address: "R. Gonçalves de Magalhães, 699 - Imbiribeira",
                                       time: "06-23",
                                       distance: nil),
                              Location(name: "Orla de Boa Viagem",
                                       coordinate: <#T##CLLocationCoordinate2D#>,
                                       sport: PinSports.tenis,
                                       category: "Quadra de Tênis",
                                       free: true,
                                       address: "em frente a Av. Boa Viagem, 998 - Boa Viagem",
                                       time: nil,
                                       distance: nil),
                              Location(name: "Squash Tenis Center",
                                       coordinate: <#T##CLLocationCoordinate2D#>,
                                       sport: PinSports.tenis,
                                       category: "Tênis Clube",
                                       free: false,
                                       address: "Rua Dr. Luiz Correia de Oliveira, 375 - Boa Viagem",
                                       time: "06-23",
                                       distance: nil),
                              Location(name: "Match Point",
                                       coordinate: <#T##CLLocationCoordinate2D#>,
                                       sport: PinSports.tenis,
                                       category: "Tênis Clube",
                                       free: false,
                                       address: "R. Dom João Costa, 300 - Torreão",
                                       time: "06-22",
                                       distance: nil),
                              Location(name: "Royal Tenis Club",
                                       coordinate: <#T##CLLocationCoordinate2D#>,
                                       sport: PinSports.tenis,
                                       category: "Tênis Clube",
                                       free: false,
                                       address: "R. dos Arcos, 116 - Poço da Panela",
                                       time: "06-22",
                                       distance: nil)
                              
        ]
        modelDict["Basquete"] = [Location(name: "Parque Santana",
                                       coordinate: <#T##CLLocationCoordinate2D#>,
                                       sport: PinSports.basquete,
                                       category: "Quadra de Basquete",
                                       free: true,
                                       address: "R. Jorge Gomes de Sá - Santana",
                                       time: "05-21",
                                       distance: nil),
                              Location(name: "Dois Irmãos Arena",
                                       coordinate: <#T##CLLocationCoordinate2D#>,
                                       sport: PinSports.basquete,
                                       category: "Quadra de Tênis",
                                       free: false,
                                       address: "R. Dois Irmãos, 1020 - Dois Irmãos",
                                       time: "06-22",
                                       distance: nil),
                              Location(name: "Arena Beach Basketball do Pina",
                                       coordinate: <#T##CLLocationCoordinate2D#>,
                                       sport: PinSports.basquete,
                                       category: "Quadra de Basquete",
                                       free: false,
                                       address: "em frente a Av. Boa Viagem, 666 - Boa Viagem",
                                       time: nil,
                                       distance: nil),
                              Location(name: "Basketball PE",
                                       coordinate: <#T##CLLocationCoordinate2D#>,
                                       sport: PinSports.basquete,
                                       category: "Quadra de Basquete, Praça Pública",
                                       free: false,
                                       address: "R. Felipe de Oliveira, 99 - Imbiribeira",
                                       time: nil,
                                       distance: nil)
        ]
        modelDict["Corrida"] = [Location(name: "Parque da Jaqueira",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.corrida,
                                         category: "Parque ao ar livre",
                                         free: true,
                                         address: "R. do Futuro - Graças",
                                         time: "04-22",
                                         distance: nil),
                                Location(name: "Avenida Boa Viagem",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.corrida,
                                         category: "Orla de praia",
                                         free: true,
                                         address: "Av. Boa Viagem - Boa Viagem",
                                         time: nil,
                                         distance: nil),
                                Location(name: "Parque Urbano da Macaxeira",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.corrida,
                                         category: "Parque ao ar livre",
                                         free: true,
                                         address: "Av. Norte Miguel Arraes de Alencar, s/n - Macaxeira",
                                         time: "05-22",
                                         distance: nil),
                                Location(name: "Praça de Casa Forte",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.corrida,
                                         category: "Parque ao ar livre",
                                         free: true,
                                         address: "Av. Dezessete de Agosto, 1387 - Parnamirim",
                                         time: nil,
                                         distance: nil),
                                Location(name: "Lagoa do Araçá",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.corrida,
                                         category: "Parque ao ar livre",
                                         free: true,
                                         address: "Lagoa do Araçá - Imbiribeira",
                                         time: nil,
                                         distance: nil),
                                Location(name: "Praça da Várzea",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.corrida,
                                         category: "Praça pública",
                                         free: true,
                                         address: "Praça da Várzea - Várzea",
                                         time: nil,
                                         distance: nil)
            ]
        
        modelDict["Skate"] = [Location(name: "Mini Ramp Lagoa do Araçá",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                       sport: PinSports.skate,
                                         category: "Pista de Skate",
                                         free: true,
                                         address: "Av. José Ferreira Lins - Imbiribeira",
                                         time: "04-22",
                                         distance: nil),
                                Location(name: "Skate Park Marcelo Lyra",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.skate,
                                         category: "Parque de Skate",
                                         free: true,
                                         address: "em frente a Av. Boa Viagem, 666 - Boa Viagem",
                                         time: nil,
                                         distance: nil),
                                Location(name: "Loa Restô",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.skate,
                                         category: "Pista de Skate, Bar",
                                         free: false,
                                         address: "R. Esmeraldino Bandeira, número 68 - Graças",
                                         time: "12-00",
                                         distance: nil),
                                Location(name: "Skate Park Aurora",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.skate,
                                         category: "Parque de Skate",
                                         free: true,
                                         address: "R. da Aurora, 998 - Boa Vista",
                                         time: nil,
                                         distance: nil),
                                Location(name: "Skatepark do Santana",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.skate,
                                         category: "Parque de Skate",
                                         free: true,
                                         address: "R. Jorge Gomes de Sá - Santana",
                                         time: "05-21",
                                         distance: nil),
                                Location(name: "Pista de Skate da Caxangá",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.skate,
                                         category: "Pista de Skate",
                                         free: true,
                                         address: "Av. Caxangá, 4501 - Madalena",
                                         time: nil,
                                         distance: nil),
        ]
        modelDict["Ciclismo"] = [Location(name: "Parque da Jaqueira",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                          sport: PinSports.bicicleta,
                                         category: "Parque ao ar livre",
                                         free: true,
                                         address: "R. do Futuro - Graças",
                                         time: "04-22",
                                         distance: nil),
                                Location(name: "Avenida Boa Viagem",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.bicicleta,
                                         category: "Orla de praia",
                                         free: true,
                                         address: "Av. Boa Viagem - Boa Viagem",
                                         time: nil,
                                         distance: nil),
                                Location(name: "Parque Urbano da Macaxeira",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.bicicleta,
                                         category: "Parque ao ar livre",
                                         free: true,
                                         address: "Av. Norte Miguel Arraes de Alencar, s/n - Macaxeira",
                                         time: "05-22",
                                         distance: nil),
                                Location(name: "Praça de Casa Forte",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.bicicleta,
                                         category: "Parque ao ar livre",
                                         free: false,
                                         address: "Av. Dezessete de Agosto, 1387 - Parnamirim",
                                         time: nil,
                                         distance: nil),
                                Location(name: "Lagoa do Araçá",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.bicicleta,
                                         category: "Parque ao ar livre",
                                         free: true,
                                         address: "Lagoa do Araçá - Imbiribeira",
                                         time: nil,
                                         distance: nil),
                                Location(name: "Praça da Várzea",
                                         coordinate: <#T##CLLocationCoordinate2D#>,
                                         sport: PinSports.bicicleta,
                                         category: "Praça pública",
                                         free: false,
                                         address: "Praça da Várzea - Várzea",
                                         time: nil,
                                         distance: nil),
                                 Location(name: "Lagoa do Araçá",
                                          coordinate: <#T##CLLocationCoordinate2D#>,
                                          sport: PinSports.bicicleta,
                                          category: "Parque ao ar livre",
                                          free: true,
                                          address: "Lagoa do Araçá - Imbiribeira",
                                          time: nil,
                                          distance: nil),
                                 Location(name: "Praça da Várzea",
                                          coordinate: <#T##CLLocationCoordinate2D#>,
                                          sport: PinSports.bicicleta,
                                          category: "Praça pública",
                                          free: false,
                                          address: "Praça da Várzea - Várzea",
                                          time: nil,
                                          distance: nil)
        ]
    }
}
