//
//  LocationStore.swift
//  Qatar-Challenge WatchKit Extension
//
//  Created by acrn on 30/11/22.
//

import Foundation
import MapKit

class LocationStore {
    
    var modelDict = [String: [Location]]()
    
    init() {
        modelDict["Futebol"] = [Location(name: "Arena Recife",
                                         coordinate: CLLocationCoordinate2D(latitude: -8.042511416608455, longitude: -34.92634404282216),
                                         sport: PinSports.futebol,
                                         category: "Campo de Futebol",
                                         free: false,
                                         address: "R. Álvares Píres, 16 - Cordeiro",
                                         time: "07-23",
                                         asset: "futebolBlue",
                                         distance: nil),
                                Location(name: "Campo do Bueirão",
                                         coordinate: CLLocationCoordinate2D(latitude: -8.045798529723339, longitude: -34.913972631342304),
                                         sport: PinSports.futebol,
                                         category: "Campo de Futebol",
                                         free: false,
                                         address: "R. Zilda S de Santana - Torre",
                                         time: "07-23:30",
                                         asset: "futebolBlue",
                                         distance: nil),
                                Location(name: "Campo Cacique",
                                         coordinate: CLLocationCoordinate2D(latitude: -8.052426064053531, longitude: -34.913682902506075),
                                         sport: PinSports.futebol,
                                         category: "Campo de Futebol",
                                         free: true,
                                         address: "Tv. Dr. Amaríles Barbosa de Águiar - Madalena",
                                         time: nil,
                                         asset: "futebolBlue",
                                         distance: nil),
                                Location(name: "Society do Clube Internacional",
                                         coordinate: CLLocationCoordinate2D(latitude: -8.058698267834648, longitude: -34.9034517583249),
                                         sport: PinSports.futebol,
                                         category: "Campo de Futebol",
                                         free: false,
                                         address: "R. Prof. Benedito Monteiro, 56 - Madalena",
                                         time: "15-00",
                                         asset: "futebolBlue",
                                         distance: nil),
                                Location(name: "Arena Bongi Society",
                                         coordinate: CLLocationCoordinate2D(latitude: -8.064160944011116, longitude: -34.92072477366971),
                                         sport: PinSports.futebol,
                                         category: "Campo de futebol",
                                         free: false,
                                         address: "R. Isaac Markman, 432 - Bongi",
                                         time: "15-22",
                                         asset: "futebolBlue",
                                         distance: nil),
                                Location(name: "Play Side",
                                         coordinate: CLLocationCoordinate2D(latitude: -8.126699672285513, longitude: -34.90790458716063),
                                         sport: PinSports.futebol,
                                         category: "Campo de futebol",
                                         free: false,
                                         address: "R. Amália Bernardino de Sousa, 137 - Boa Viagem",
                                         time: "08-22:30",
                                         asset: "futebolBlue",
                                         distance: nil),
                                Location(name: "Arena X1",
                                         coordinate: CLLocationCoordinate2D(latitude: -8.04292506167884, longitude: -34.944126644833815),
                                         sport: PinSports.futebol,
                                         category: "Campo de futebol",
                                         free: false,
                                         address: "R. Agricolândia, 64 - Várzea",
                                         time: "08-22",
                                         asset: "futebolBlue",
                                         distance: nil)
        ]
        modelDict["Corrida"] = [Location(name: "Parque da Jaqueira",
                                         coordinate: CLLocationCoordinate2D(latitude: -8.036995008557088, longitude: -34.90483639527013),
                                         sport: PinSports.corrida,
                                         category: "Parque ao ar livre",
                                         free: true,
                                         address: "R. do Futuro - Graças",
                                         time: "04-22",
                                         asset: "corridaBlue",
                                         distance: nil),
                                Location(name: "Avenida Boa Viagem",
                                         coordinate: CLLocationCoordinate2D(latitude: -8.123907897798611, longitude: -34.89678113134159),
                                         sport: PinSports.corrida,
                                         category: "Orla de praia",
                                         free: true,
                                         address: "Av. Boa Viagem - Boa Viagem",
                                         time: nil,
                                         asset: "corridaBlue",
                                         distance: nil),
                                Location(name: "Parque Urbano da Macaxeira",
                                         coordinate: CLLocationCoordinate2D(latitude: -8.01524372604699, longitude: -34.93191426625682),
                                         sport: PinSports.corrida,
                                         category: "Parque ao ar livre",
                                         free: true,
                                         address: "Av. Norte Miguel Arraes de Alencar, s/n - Macaxeira",
                                         time: "05-22",
                                         asset: "corridaBlue",
                                         distance: nil),
                                Location(name: "Praça de Casa Forte",
                                         coordinate: CLLocationCoordinate2D(latitude: -8.034709135537076, longitude: -34.91949448901472),
                                         sport: PinSports.corrida,
                                         category: "Parque ao ar livre",
                                         free: true,
                                         address: "Av. Dezessete de Agosto, 1387 - Parnamirim",
                                         time: nil,
                                         asset: "corridaBlue",
                                         distance: nil),
                                Location(name: "Lagoa do Araçá",
                                         coordinate: CLLocationCoordinate2D(latitude: -8.09447071925511, longitude: -34.91349671262572),
                                         sport: PinSports.corrida,
                                         category: "Parque ao ar livre",
                                         free: true,
                                         address: "Lagoa do Araçá - Imbiribeira",
                                         time: nil,
                                         asset: "corridaBlue",
                                         distance: nil),
                                Location(name: "Praça da Várzea",
                                         coordinate: CLLocationCoordinate2D(latitude: -8.049072892257954, longitude: -34.959486219835014),
                                         sport: PinSports.corrida,
                                         category: "Praça pública",
                                         free: true,
                                         address: "Praça da Várzea - Várzea",
                                         time: nil,
                                         asset: "corridaBlue",
                                         distance: nil)
        ]
        modelDict["Tenis"] = [Location(name: "Recife Tenis Club",
                                       coordinate: CLLocationCoordinate2D(latitude: -8.12204588197846, longitude: -34.92007980306745),
                                       sport: PinSports.tenis,
                                       category: "Tênis Clube",
                                       free: false,
                                       address: "R. Gonçalves de Magalhães, 699 - Imbiribeira",
                                       time: "06-23",
                                       asset: "tenisBlue",
                                       distance: nil),
                              Location(name: "Orla de Boa Viagem",
                                       coordinate: CLLocationCoordinate2D(latitude: -8.099984823579819, longitude: -34.884993031902944),
                                       sport: PinSports.tenis,
                                       category: "Quadra de Tênis",
                                       free: true,
                                       address: "em frente a Av. Boa Viagem, 998 - Boa Viagem",
                                       time: nil,
                                       asset: "tenisBlue",
                                       distance: nil),
                              Location(name: "Squash Tenis Center",
                                       coordinate: CLLocationCoordinate2D(latitude: -8.129060873115186, longitude: -34.91284170306758),
                                       sport: PinSports.tenis,
                                       category: "Tênis Clube",
                                       free: false,
                                       address: "Rua Dr. Luiz Correia de Oliveira, 375 - Boa Viagem",
                                       time: "06-23",
                                       asset: "tenisBlue",
                                       distance: nil),
                              Location(name: "Match Point",
                                       coordinate: CLLocationCoordinate2D(latitude: -8.03880902398345, longitude: -34.88318973190347),
                                       sport: PinSports.tenis,
                                       category: "Tênis Clube",
                                       free: false,
                                       address: "R. Dom João Costa, 300 - Torreão",
                                       time: "06-22",
                                       asset: "tenisBlue",
                                       distance: nil),
                              Location(name: "Royal Tenis Club",
                                       coordinate: CLLocationCoordinate2D(latitude: -8.034013170679659, longitude: -34.92351550306801),
                                       sport: PinSports.tenis,
                                       category: "Tênis Clube",
                                       free: false,
                                       address: "R. dos Arcos, 116 - Poço da Panela",
                                       time: "06-22",
                                       asset: "tenisBlue",
                                       distance: nil)
                              
        ]
        modelDict["Basquete"] = [Location(name: "Parque Santana",
                                          coordinate: CLLocationCoordinate2D(latitude: -8.040899113970013, longitude: -34.91741746073889),
                                          sport: PinSports.basquete,
                                          category: "Quadra de Basquete",
                                          free: true,
                                          address: "R. Jorge Gomes de Sá - Santana",
                                          time: "05-21",
                                          asset: "basqueteBlue",
                                          distance: nil),
                                 Location(name: "Dois Irmãos Arena",
                                          coordinate: CLLocationCoordinate2D(latitude: -8.015948502176144, longitude: -34.942071360739035),
                                          sport: PinSports.basquete,
                                          category: "Quadra de Tênis",
                                          free: false,
                                          address: "R. Dois Irmãos, 1020 - Dois Irmãos",
                                          time: "06-22",
                                          asset: "basqueteBlue",
                                          distance: nil),
                                 Location(name: "Arena Beach Basketball do Pina",
                                          coordinate: CLLocationCoordinate2D(latitude: -8.097518406705415, longitude: -34.88377333190304),
                                          sport: PinSports.basquete,
                                          category: "Quadra de Basquete",
                                          free: false,
                                          address: "em frente a Av. Boa Viagem, 666 - Boa Viagem",
                                          time: nil,
                                          asset: "basqueteBlue",
                                          distance: nil),
                                 Location(name: "Basketball PE",
                                          coordinate: CLLocationCoordinate2D(latitude: -8.11695807061685, longitude: -34.91713749084868),
                                          sport: PinSports.basquete,
                                          category: "Quadra de Basquete, Praça Pública",
                                          free: false,
                                          address: "R. Felipe de Oliveira, 99 - Imbiribeira",
                                          time: nil,
                                          asset: "basqueteBlue",
                                          distance: nil)
        ]

        modelDict["Skate"] = [Location(name: "Mini Ramp Lagoa do Araçá",
                                       coordinate: CLLocationCoordinate2D(latitude: -8.092552199554815, longitude: -34.91553116506976),
                                       sport: PinSports.skate,
                                       category: "Pista de Skate",
                                       free: true,
                                       address: "Av. José Ferreira Lins - Imbiribeira",
                                       time: "04-22",
                                       asset: "skateBlue",
                                       distance: nil),
                              Location(name: "Skate Park Marcelo Lyra",
                                       coordinate: CLLocationCoordinate2D(latitude: -8.09756709133159, longitude: -34.883278960177925),
                                       sport: PinSports.skate,
                                       category: "Parque de Skate",
                                       free: true,
                                       address: "em frente a Av. Boa Viagem, 666 - Boa Viagem",
                                       time: nil,
                                       asset: "skateBlue",
                                       distance: nil),
                              Location(name: "Loa Restô",
                                       coordinate: CLLocationCoordinate2D(latitude: -8.046745030218858, longitude: -34.899458158325196),
                                       sport: PinSports.skate,
                                       category: "Pista de Skate, Bar",
                                       free: false,
                                       address: "R. Esmeraldino Bandeira, número 68 - Graças",
                                       time: "12-00",
                                       asset: "skateBlue",
                                       distance: nil),
                              Location(name: "Skate Park Aurora",
                                       coordinate: CLLocationCoordinate2D(latitude: -8.055850403948636, longitude: -34.877578267073936),
                                       sport: PinSports.skate,
                                       category: "Parque de Skate",
                                       free: true,
                                       address: "R. da Aurora, 998 - Boa Vista",
                                       time: nil,
                                       asset: "skateBlue",
                                       distance: nil),
                              Location(name: "Skatepark do Santana",
                                       coordinate: CLLocationCoordinate2D(latitude: -8.042031197712221, longitude: -34.916551344833756),
                                       sport: PinSports.skate,
                                       category: "Parque de Skate",
                                       free: true,
                                       address: "R. Jorge Gomes de Sá - Santana",
                                       time: "05-21",
                                       asset: "skateBlue",
                                       distance: nil),
                              Location(name: "Pista de Skate da Caxangá",
                                       coordinate: CLLocationCoordinate2D(latitude: -8.037335982884096, longitude: -34.94535715398555),
                                       sport: PinSports.skate,
                                       category: "Pista de Skate",
                                       free: true,
                                       address: "Av. Caxangá, 4501 - Madalena",
                                       time: nil,
                                       asset: "skateBlue",
                                       distance: nil),
        ]
        modelDict["Ciclismo"] = [Location(name: "Parque da Jaqueira",
                                          coordinate: CLLocationCoordinate2D(latitude: -8.036380986191366, longitude: -34.903884661232176),
                                          sport: PinSports.bicicleta,
                                          category: "Parque ao ar livre, ciclovia",
                                          free: true,
                                          address: "R. do Futuro - Graças",
                                          time: "04-22",
                                          asset: "bicicletaBlue",
                                          distance: nil),
                                 Location(name: "UFPE",
                                          coordinate: CLLocationCoordinate2D(latitude: -8.052309248090685, longitude: -34.94510383190341),
                                          sport: PinSports.bicicleta,
                                          category: "Cidade Universitária, ciclovia",
                                          free: true,
                                          address: "Av. Prof. Moraes Rego, 1235 - Cidade Universitária",
                                          time: nil,
                                          asset: "bicicletaBlue",
                                          distance: nil),
                                 Location(name: "Pier dos ciclistas",
                                          coordinate: CLLocationCoordinate2D(latitude: -8.071392578449034, longitude: -34.87651280306784),
                                          sport: PinSports.bicicleta,
                                          category: "Ciclofaixa pública",
                                          free: true,
                                          address: "Cais Santa Rita, 595 - São José",
                                          time: "05-22",
                                          asset: "bicicletaBlue",
                                          distance: nil),
                                 Location(name: "Boulevard Rio Brnaco",
                                          coordinate: CLLocationCoordinate2D(latitude: -8.0626966069191, longitude: -34.87295501840935),
                                          sport: PinSports.bicicleta,
                                          category: "Ciclofaixa, aluguel de bicicleta",
                                          free: true,
                                          address: "Av. Rio Branco, 155-27 - Recife",
                                          time: nil,
                                          asset: "bicicletaBlue",
                                          distance: nil),
                                 Location(name: "Bike Itaú",
                                          coordinate: CLLocationCoordinate2D(latitude: -8.053676012243065, longitude: -34.94709473448646),
                                          sport: PinSports.bicicleta,
                                          category: "Aluguel de bicicleta",
                                          free: true,
                                          address: "Casa do Estudante UFPE, 79 - Cidade Universitária",
                                          time: nil,
                                          asset: "bicicletaBlue",
                                          distance: nil),
                                 Location(name: "Avenida Boa Viagem",
                                          coordinate: CLLocationCoordinate2D(latitude: -8.126469646444301, longitude: -34.897683860738255),
                                          sport: PinSports.bicicleta,
                                          category: "Orla de praia, ciclovia",
                                          free: false,
                                          address: "Avenida Boa Viagem, s/n - Boa Viagem",
                                          time: nil,
                                          asset: "bicicletaBlue",
                                          distance: nil),
                                 Location(name: "Bike Itaú",
                                          coordinate: CLLocationCoordinate2D(latitude: -8.050510138931529, longitude: -34.95321964897277),
                                          sport: PinSports.bicicleta,
                                          category: "Aluguel de bicicleta",
                                          free: true,
                                          address: "Restaurante Universitário UFPE - Cidade Universitária",
                                          time: nil,
                                          asset: "bicicletaBlue",
                                          distance: nil),
                                 Location(name: "Praça da Várzea",
                                          coordinate: CLLocationCoordinate2D(latitude: -8.049072892257954, longitude: -34.959486219835014),
                                          sport: PinSports.bicicleta,
                                          category: "Praça pública",
                                          free: false,
                                          address: "Praça da Várzea - Várzea",
                                          time: nil,
                                          asset: "bicicletaBlue",
                                          distance: nil)
        ]
        modelDict["Musculacao"] = [Location(name: "Academia da Cidade",
                                            coordinate: CLLocationCoordinate2D(latitude: -8.049499051427125, longitude: -34.95965163272757),
                                            sport: PinSports.musculacao,
                                            category: "Academia Pública",
                                            free: true,
                                            address: "R. Azeredo Coutinho, 2126 - Várzea",
                                            time: nil,
                                            asset: "musculacaoBlue",
                                            distance: nil),
                                   Location(name: "Academia Plataforma",
                                            coordinate: CLLocationCoordinate2D(latitude: -8.042534142326975, longitude: -34.94809289657836),
                                            sport: PinSports.musculacao,
                                            category: "Academia Privada",
                                            free: false,
                                            address: "R. Abatia, 121 - Várzea",
                                            time: "06-23",
                                            asset: "musculacaoBlue",
                                            distance: nil),
                                   Location(name: "ACTO Academia",
                                            coordinate: CLLocationCoordinate2D(latitude: -8.041360222686096, longitude: -34.95829121169807),
                                            sport: PinSports.musculacao,
                                            category: "Academia Privada",
                                            free: false,
                                            address: "Av. Afonso Olindense, 1090 - Várzea",
                                            time: "05-23",
                                            asset: "musculacaoBlue",
                                            distance: nil),
                                   Location(name: "Unit Academia",
                                            coordinate: CLLocationCoordinate2D(latitude: -8.039890898745742, longitude: -34.94623670250622),
                                            sport: PinSports.musculacao,
                                            category: "Academia Privada",
                                            free: false,
                                            address: "R. Gen. Polidoro, 335 - Várzea",
                                            time: "05-23",
                                            asset: "musculacaoBlue",
                                            distance: nil),
                                   Location(name: "Avenida Boa Viagem",
                                            coordinate: CLLocationCoordinate2D(latitude: -8.10588582621721, longitude: -34.88698948901393),
                                            sport: PinSports.musculacao,
                                            category: "Academia Pública",
                                            free: true,
                                            address: "Avenida Boa Viagem, s/n - Boa Viagem",
                                            time: nil,
                                            asset: "musculacaoBlue",
                                            distance: nil)
        ]
        modelDict["Volei"] = [Location(name: "Arena Lob",
                                       coordinate: CLLocationCoordinate2D(latitude: -8.041557630852049, longitude: -34.911301474232616),
                                       sport: PinSports.volei,
                                       category: "Clube de esportes",
                                       free: false,
                                       address: "R. Real da Torre, 1761 - Torre",
                                       time: "06-00",
                                       asset: "voleiBlue",
                                       distance: nil),
                              Location(name: "Prainha ZN",
                                       coordinate: CLLocationCoordinate2D(latitude: -8.048517946905793, longitude: -34.910541560738686),
                                       sport: PinSports.volei,
                                       category: "Clube de esportes",
                                       free: false,
                                       address: "R. Ernâni Braga, 555 - Madalena",
                                       time: "06-23",
                                       asset: "voleiBlue",
                                       distance: nil),
                              Location(name: "FPS Sports",
                                       coordinate: CLLocationCoordinate2D(latitude: -8.128535331008493, longitude: -34.91428514539661),
                                       sport: PinSports.volei,
                                       category: "Clube de esportes",
                                       free: false,
                                       address: "Av. Mal. Mascarenhas de Morais, 4989 - Boa Viagem",
                                       time: "06-22",
                                       asset: "voleiBlue",
                                       distance: nil),
                              Location(name: "FPS Sports",
                                       coordinate: CLLocationCoordinate2D(latitude: -8.037039076935754, longitude: -34.89537957423275),
                                       sport: PinSports.volei,
                                       category: "Clube de esportes",
                                       free: false,
                                       address: "R. Gomes de Matos Júnior, 116 - Aflitos",
                                       time: "06-22",
                                       asset: "voleiBlue",
                                       distance: nil),
                              Location(name: "Quadras UFPE",
                                       coordinate: CLLocationCoordinate2D(latitude: -8.054975940172623, longitude: -34.947962731903466),
                                       sport: PinSports.volei,
                                       category: "Quadras de vôlei",
                                       free: false,
                                       address: "Cidade Universitária",
                                       time: "06-18",
                                       asset: "voleiBlue",
                                       distance: nil),
                              Location(name: "Vôlei De Praia De Marinheiro",
                                       coordinate: CLLocationCoordinate2D(latitude: -8.132245436233875, longitude: -34.90011601871844),
                                       sport: PinSports.volei,
                                       category: "Quadras de vôlei de praia",
                                       free: true,
                                       address: "Em frente a Av. Boa Viagem, 760 - Boa Viagem",
                                       time: "06-18",
                                       asset: "voleiBlue",
                                       distance: nil),
                              Location(name: "Arena Várzea",
                                       coordinate: CLLocationCoordinate2D(latitude: -8.036085216872584, longitude: -34.95730677371228),
                                       sport: PinSports.volei,
                                       category: "Quadras de vôlei",
                                       free: true,
                                       address: "R. Amoroso Costa, 130-200 - Várzea, Recife - PE",
                                       time: "06-22",
                                       asset: "voleiBlue",
                                       distance: nil)
        ]
        modelDict["Nataçao"] = [Location(name: "Via Água Club",
                                         coordinate: CLLocationCoordinate2D(latitude: -8.029228710894643, longitude: -34.91358429376224),
                                         sport: PinSports.natacao,
                                         category: "Escolinha de natação",
                                         free: false,
                                         address: "R. Dona Rosa da Fonseca - Casa Amarela",
                                         time: "06-20",
                                         asset: "natacaoBlue",
                                         distance: nil),
                                Location(name: "Nikita Fitness",
                                         coordinate: CLLocationCoordinate2D(latitude: -8.106908848290018, longitude: -34.89277241599695),
                                         sport: PinSports.natacao,
                                         category: "Escolinha de natação",
                                         free: false,
                                         address: "R. Aviador Severiano Lins, 102 - Boa Viagem",
                                         time: "06-21",
                                         asset: "natacaoBlue",
                                         distance: nil),
                                Location(name: "Academia Cia Athletica",
                                         coordinate: CLLocationCoordinate2D(latitude: -8.085839739414402, longitude: -34.89450333134189),
                                         sport: PinSports.natacao,
                                         category: "Academia com piscina",
                                         free: false,
                                         address: "Av. República do Líbano, 251 - Pina",
                                         time: "05-23",
                                         asset: "natacaoBlue",
                                         distance: nil),
                                Location(name: "NEFD - Núcleo de Educação Física e Desportos",
                                         coordinate: CLLocationCoordinate2D(latitude: -8.068928414620624, longitude: -34.94840625433492),
                                         sport: PinSports.natacao,
                                         category: "Piscina universitária",
                                         free: false,
                                         address: "Cidade Universitária, Recife - PE",
                                         time: "06-18",
                                         asset: "natacaoBlue",
                                         distance: nil),
                                Location(name: "Ciafit Family Club",
                                         coordinate: CLLocationCoordinate2D(latitude: -8.068928414620624, longitude: -34.94840625433492),
                                         sport: PinSports.natacao,
                                         category: "Academia com piscina",
                                         free: false,
                                         address: "Estrada do Forte do Arraial N. do B Jesus, 477 - Cordeiro",
                                         time: "05-23",
                                         asset: "natacaoBlue",
                                         distance: nil)
        ]
    }
}
